# Dockerfile.deploy
FROM ubuntu:focal

RUN apt-get update
RUN apt-get install -y curl

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs

WORKDIR /home/app

# Copy the deployment script
COPY script.js script.js
COPY package*.json .

RUN npm install

CMD ["node", "script.js"]
